### ISSUE TITLE
ImportError: could not import gobject (could not find _PyGObject_API object)

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-launcher#20]
# migasfree-tray
Traceback (most recent call last):
  File "/usr/bin/migasfree-tray", line 47, in <module>
    from migasfree_client.utils import execute
  File "/usr/lib/python2.7/dist-packages/migasfree_client/__init__.py", line 56, in <module>
    import pango
ImportError: could not import gobject (could not find _PyGObject_API object)

Detectado con ubuntu mate (15.04)

**Comment by agacias** [comment]
También ocurre en ubuntu (15.04), tanto con unity como con 'gnome flashbask metacity'
